server:
  port: 8000

eureka:
  instance:
    instance-id: gateway-instance
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

spring: 
  cloud:
   gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE 
          predicates:
            - Path=/auth/** 
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}       
                  
        - id: demo-service
          uri: lb://DEMO-SERVICE 
          predicates:
            - Path=/demo/** 
          filters:
            - RewritePath=/demo/?(?<segment>.*), /$\{segment}        

management:
  endpoints:
   web:
    exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
